export const ROLES = {
  civilian: {
    id: "civilian",
    name: "Mještanin",
    namePlural: "Mještani",
    team: "village",
    color: "#52b788",
    bgColor: "#1b4332",
    icon: "account-group-outline",
    nightAction: false,
    nightOrder: null,
    nightGroup: null,
    maxCount: 10,
    description:
      "Obični mještanin bez posebnih moći. Preživite i pomozite eliminirati mafiju!",
    cardDescription:
      "Tvojim glasom na sudu leži sudbina svih. Pronađi mafiju i eliminiraj ih!",
    nightText: null,
    audioKey: null,
    audioSleepKey: null,
    actionText: null,
    actionVerb: null,
    showResultToPlayer: false,
  },
  mafia: {
    id: "mafia",
    name: "Mafija",
    namePlural: "Mafija",
    team: "mafia",
    color: "#e63946",
    bgColor: "#370617",
    icon: "skull-outline",
    nightAction: true,
    nightOrder: 2,
    nightGroup: "mafia",
    maxCount: 20,
    description: "Svake noći eliminira jednog mještanina.",
    cardDescription:
      "Ti si mafija! Surađuj s timom i eliminiraj mještane svake noći, a danju se pretvari da si nevin.",
    nightText: "Mafija se budi...\nOdaberite žrtvu za ovu noć.",
    audioKey: "mafia_wake",
    audioSleepKey: "mafia_sleep",
    actionText: "Mafija bira žrtvu",
    actionVerb: "Ubij",
    showResultToPlayer: false,
  },
  don: {
    id: "don",
    name: "Don",
    namePlural: "Don",
    team: "mafia",
    color: "#c1121f",
    bgColor: "#370617",
    icon: "diamond-outline",
    nightAction: true,
    nightOrder: 2,
    nightGroup: "mafia",
    maxCount: 1,
    description: "Vođa mafije. Policiji izgleda kao nevin mještanin.",
    cardDescription:
      "Ti si Don - vođa mafije! Nijedna istraga te ne može otkriti. Koordiniraj tim i pobijedi mještane.",
    nightText: null,
    audioKey: null,
    audioSleepKey: null,
    actionText: null,
    actionVerb: null,
    showResultToPlayer: false,
  },
  doctor: {
    id: "doctor",
    name: "Doktor",
    namePlural: "Doktori",
    team: "village",
    color: "#4cc9f0",
    bgColor: "#03045e",
    icon: "medical-bag",
    nightAction: true,
    nightOrder: 3,
    nightGroup: "doctor",
    maxCount: 2,
    description: "Svake noći spašava jednog igrača od mafijine žrtve.",
    cardDescription:
      "Ti si Doktor! Svake noći možeš spasiti jednog igrača od mafije. Možeš spasiti i sebe!",
    nightText: "Doktor se budi...\nOdaberite koga ćete spasiti ove noći.",
    audioKey: "doctor_wake",
    audioSleepKey: "doctor_sleep",
    actionText: "Doktor bira koga spašava",
    actionVerb: "Spasi",
    showResultToPlayer: false,
  },
  police: {
    id: "police",
    name: "Policajac",
    namePlural: "Policija",
    team: "village",
    color: "#ffd166",
    bgColor: "#7f4f24",
    icon: "police-badge-outline",
    nightAction: true,
    nightOrder: 4,
    nightGroup: "police",
    maxCount: 2,
    description: "Svake noći istražuje igrača - saznaje je li mafija ili ne.",
    cardDescription:
      "Ti si Policajac! Svake noći istražuješ jednog sumnjivca i saznaješ je li mafija. Rezultat ostaje tajan!",
    nightText: "Policajac se budi...\nOdaberite koga ćete istražiti.",
    audioKey: "police_wake",
    audioSleepKey: "police_sleep",
    actionText: "Policajac istražuje",
    actionVerb: "Istraži",
    showResultToPlayer: true,
  },
  lady: {
    id: "lady",
    name: "Dama",
    namePlural: "Dame",
    team: "mafia",
    color: "#c77dff",
    bgColor: "#3d0066",
    icon: "heart-outline",
    nightAction: true,
    nightOrder: 1,
    nightGroup: "lady",
    maxCount: 1,
    description:
      "Svake noći ušuti jednog igrača — taj igrač ne smije pričati sljedeći dan.",
    cardDescription:
      "Ti si Dama! Svojom čari ušuti jednog igrača svake noći. Odabrani igrač ne smije govoriti cijeli sljedeći dan!",
    nightText: "Dama se budi...\nOdaberite koga ćete ušutiti ove noći.",
    audioKey: "lady_wake",
    audioSleepKey: "lady_sleep",
    actionText: "Dama bira koga ušućuje",
    actionVerb: "Ušuti",
    showResultToPlayer: false,
  },
};

// Night action groups - defines display order and which roles act together
export const NIGHT_GROUPS = [
  {
    id: "lady",
    roles: ["lady"],
    nightOrder: 1,
    wakeText: "Dama se budi...",
    sleepText: "Dama zaspi.",
    audioKey: "lady_wake",
    audioSleepKey: "lady_sleep",
  },
  {
    id: "mafia",
    roles: ["mafia", "don"],
    nightOrder: 2,
    wakeText: "Mafija se budi...",
    sleepText: "Mafija zaspi.",
    audioKey: "mafia_wake",
    audioSleepKey: "mafia_sleep",
  },
  {
    id: "doctor",
    roles: ["doctor"],
    nightOrder: 3,
    wakeText: "Doktor se budi...",
    sleepText: "Doktor zaspi.",
    audioKey: "doctor_wake",
    audioSleepKey: "doctor_sleep",
  },
  {
    id: "police",
    roles: ["police"],
    nightOrder: 4,
    wakeText: "Policajac se budi...",
    sleepText: "Policajac zaspi.",
    audioKey: "police_wake",
    audioSleepKey: "police_sleep",
  },
];

export const NARRATION = {
  night_start: "Noć je pala na grad...\nSvi zatvaraju oči i miruju u tišini.",
  day_start: "Jutro je nastupilo.\nSvi se bude i otvaraju oči.",
  nobody_killed: "Sinoć nitko nije ubijen.\nMještani odahnuše s olakšanjem.",
  player_killed: (name) =>
    `Sinoć je pronađen mrtav: ${name}.\nMještani su preplavljeni tugom i strahom.`,
  mafia_wins: "Mafija je pobijedila!\nPreuzeli su kontrolu nad gradom.",
  village_wins:
    "Mještani su pobijedili!\nMafija je eliminirana, grad je slobodan!",
};
